from route.atendimento.analista import configure_analista_routes
from route.atendimento.processo import configure_processo_routes
from route.atendimento.atividade import configure_atividade_routes

from route.local.empresa import configure_empresa_routes
from route.local.unidade import configure_unidade_routes
from route.local.area import configure_area_routes